In [1]:
from google.colab import files


uploaded = files.upload()

Saving Churn_Modelling.csv to Churn_Modelling.csv

In [7]:
import numpy as np
import pandas as pd

df=pd.read_csv('Churn_Modelling.csv')
df.head()

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,2,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,3,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,4,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,5,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0

In [3]:
df.tail()

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
9995,9996,15606229,Obijiaku,771,France,Male,39,5,0.00,2,1,0,96270.64,0
9996,9997,15569892,Johnstone,516,France,Male,35,10,57369.61,1,1,1,101699.77,0
9997,9998,15584532,Liu,709,France,Female,36,7,0.00,1,0,1,42085.58,1
9998,9999,15682355,Sabbatini,772,Germany,Male,42,3,75075.31,2,1,0,92888.52,1
9999,10000,15628319,Walker,792,France,Female,28,4,130142.79,1,1,0,38190.78,0

In [6]:
column_data = df["Age"]
print(column_data)

0       42
1       41
2       42
3       39
4       43
        ..
9995    39
9996    35
9997    36
9998    42
9999    28
Name: Age, Length: 10000, dtype: int64

In [14]:


age_column = df["Age"]


min_range = 0
max_range = 1


min_age = age_column.min()
max_age = age_column.max()
normalized_age = (age_column - min_age) / (max_age - min_age) * (max_range - min_range) + min_range


normalized_df = df.copy()
normalized_df["Normalized_Age"] = normalized_age


print(normalized_df.head())

   RowNumber  CustomerId   Surname  CreditScore Geography  Gender  Age  \
0          1    15634602  Hargrave          619    France  Female   42
1          2    15647311      Hill          608     Spain  Female   41
2          3    15619304      Onio          502    France  Female   42
3          4    15701354      Boni          699    France  Female   39
4          5    15737888  Mitchell          850     Spain  Female   43

   Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0       2       0.00              1          1               1
1       1   83807.86              1          0               1
2       8  159660.80              3          1               0
3       1       0.00              2          0               0
4       2  125510.82              1          1               1

   EstimatedSalary  Exited  Normalized_Age
0        101348.88       1        0.324324
1        112542.58       0        0.310811
2        113931.57       1        0.324324
3         93826.63       0        0.283784
4         79084.10       0        0.337838

In [13]:
age_column = df["Age"]

# Calculate the mean, median, mode, and standard deviation of the "Age" column
mean_age = np.mean(age_column)
median_age = np.median(age_column)
mode_age = age_column.mode()[0]
std_deviation_age = np.std(age_column)

# Standardize the "Age" column
z_score_age = (age_column - mean_age) / std_deviation_age

# Create a DataFrame to store the results
normalized_df = pd.DataFrame({
    "Original_Age": age_column,
    "Mean_Normalized_Age": (age_column - mean_age) / std_deviation_age,
    "Median_Normalized_Age": (age_column - median_age) / std_deviation_age,
    "Mode_Normalized_Age": (age_column - mode_age) / std_deviation_age
})

# Display the normalized DataFrame
print(normalized_df.head())

   Original_Age  Mean_Normalized_Age  Median_Normalized_Age  \
0            42             0.293517               0.476768
1            41             0.198164               0.381414
2            42             0.293517               0.476768
3            39             0.007457               0.190707
4            43             0.388871               0.572122

   Mode_Normalized_Age
0             0.476768
1             0.381414
2             0.476768
3             0.190707
4             0.572122

In [15]:
df["Age"]=df["Age"].astype('category')
df.head()

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,2,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,3,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,4,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,5,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0

In [25]:
df['Binary_Gender'] = (df['Gender'] == 'Male').astype(int)
df.head()
df.dtypes
pd.get_dummies('Gender')

   Gender
0       1

In [35]:
Geo=df["Geography"]
Geo.value_counts()
pd.get_dummies(Geo)

      France  Germany  Spain
0          1        0      0
1          0        0      1
2          1        0      0
3          1        0      0
4          0        0      1
...      ...      ...    ...
9995       1        0      0
9996       1        0      0
9997       1        0      0
9998       0        1      0
9999       1        0      0

[10000 rows x 3 columns]

In [36]:
Geo=df["Geography"]
geo_dummies=pd.get_dummies(Geo)
df = pd.concat([df, geo_dummies], axis=1)
df.head()

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited,Binary_Gender,Geo,Geo,France,Germany,Spain
0,1,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1,0,1.0,1.0,1,0,0
1,2,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0,0,NaN,NaN,0,0,1
2,3,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1,0,NaN,NaN,1,0,0
3,4,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0,0,NaN,NaN,1,0,0
4,5,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0,0,NaN,NaN,0,0,1

In [31]:
df.dtypes

RowNumber             int64
CustomerId            int64
Surname              object
CreditScore           int64
Geography            object
Gender               object
Age                category
Tenure                int64
Balance             float64
NumOfProducts         int64
HasCrCard             int64
IsActiveMember        int64
EstimatedSalary     float64
Exited                int64
Binary_Gender         int64
Geo                 float64
Geo                 float64
dtype: object

In [39]:
Gen=df["Gender"]
gen_dummies=pd.get_dummies(Gen)
df = pd.concat([df, gen_dummies], axis=1)
df.head()
print(gen_dummies)

      Female  Male
0          1     0
1          1     0
2          1     0
3          1     0
4          1     0
...      ...   ...
9995       0     1
9996       0     1
9997       1     0
9998       0     1
9999       1     0

[10000 rows x 2 columns]

In [43]:
Ten=df["Tenure"]
ten_dummies=pd.get_dummies(Ten)
df = pd.concat([df, ten_dummies], axis=1)
df.head()
print(ten_dummies)
#NumOfProducts

      0   1   2   3   4   5   6   7   8   9   10
0      0   0   1   0   0   0   0   0   0   0   0
1      0   1   0   0   0   0   0   0   0   0   0
2      0   0   0   0   0   0   0   0   1   0   0
3      0   1   0   0   0   0   0   0   0   0   0
4      0   0   1   0   0   0   0   0   0   0   0
...   ..  ..  ..  ..  ..  ..  ..  ..  ..  ..  ..
9995   0   0   0   0   0   1   0   0   0   0   0
9996   0   0   0   0   0   0   0   0   0   0   1
9997   0   0   0   0   0   0   0   1   0   0   0
9998   0   0   0   1   0   0   0   0   0   0   0
9999   0   0   0   0   1   0   0   0   0   0   0

[10000 rows x 11 columns]

In [42]:
nop=df["NumOfProducts"]
nop_dummies=pd.get_dummies(Ten)
df = pd.concat([df, nop_dummies], axis=1)
df.head()
print(nop_dummies)

      0   1   2   3   4   5   6   7   8   9   10
0      0   0   1   0   0   0   0   0   0   0   0
1      0   1   0   0   0   0   0   0   0   0   0
2      0   0   0   0   0   0   0   0   1   0   0
3      0   1   0   0   0   0   0   0   0   0   0
4      0   0   1   0   0   0   0   0   0   0   0
...   ..  ..  ..  ..  ..  ..  ..  ..  ..  ..  ..
9995   0   0   0   0   0   1   0   0   0   0   0
9996   0   0   0   0   0   0   0   0   0   0   1
9997   0   0   0   0   0   0   0   1   0   0   0
9998   0   0   0   1   0   0   0   0   0   0   0
9999   0   0   0   0   1   0   0   0   0   0   0

[10000 rows x 11 columns]

In [45]:
card=df["HasCrCard"]
card_dummies=pd.get_dummies(card)
df = pd.concat([df, card_dummies], axis=1)
df.head()
print(card_dummies)

      0  1
0     0  1
1     1  0
2     0  1
3     1  0
4     0  1
...  .. ..
9995  0  1
9996  0  1
9997  1  0
9998  0  1
9999  0  1

[10000 rows x 2 columns]

In [46]:
df.head()

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,...,5,6,7,8,9,10,0,1,0,1
0,1,15634602,Hargrave,619,France,Female,42,2,0.00,1,...,0,0,0,0,0,0,0,1,0,1
1,2,15647311,Hill,608,Spain,Female,41,1,83807.86,1,...,0,0,0,0,0,0,1,0,1,0
2,3,15619304,Onio,502,France,Female,42,8,159660.80,3,...,0,0,0,1,0,0,0,1,0,1
3,4,15701354,Boni,699,France,Female,39,1,0.00,2,...,0,0,0,0,0,0,1,0,1,0
4,5,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,...,0,0,0,0,0,0,0,1,0,1

In [48]:
active=df["IsActiveMember"]
active_dummies=pd.get_dummies(active)
df = pd.concat([df, active_dummies], axis=1)
df.head()
print(active_dummies)

      0  1
0     0  1
1     0  1
2     1  0
3     1  0
4     0  1
...  .. ..
9995  1  0
9996  0  1
9997  0  1
9998  1  0
9999  1  0

[10000 rows x 2 columns]

In [49]:
exit=df["Exited"]
exit_dummies=pd.get_dummies(exit)
df = pd.concat([df, exit_dummies], axis=1)
df.head()
print(exit_dummies)

      0  1
0     0  1
1     1  0
2     0  1
3     1  0
4     1  0
...  .. ..
9995  1  0
9996  1  0
9997  0  1
9998  0  1
9999  1  0

[10000 rows x 2 columns]

In [51]:
df.head()

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,...,0,1,0,1,0,1,0,1,0,1
0,1,15634602,Hargrave,619,France,Female,42,2,0.00,1,...,0,1,0,1,0,1,0,1,0,1
1,2,15647311,Hill,608,Spain,Female,41,1,83807.86,1,...,1,0,1,0,1,0,0,1,1,0
2,3,15619304,Onio,502,France,Female,42,8,159660.80,3,...,0,1,0,1,0,1,1,0,0,1
3,4,15701354,Boni,699,France,Female,39,1,0.00,2,...,1,0,1,0,1,0,1,0,1,0
4,5,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,...,0,1,0,1,0,1,0,1,1,0

WARNING:root:Quickchart encountered unexpected dtypes in columns: "(['Age', 'Geo', 'Geo', 'Female', 'Male', 'Female', 'Male', 'Female', 'Male', 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1],)"