In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [2]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [3]:
dataset=pd.read_csv(r'/content/drive/My Drive/ailab/penguins_size.csv')

In [4]:
dataset.head()

,species,island,culmen_length_mm,culmen_depth_mm,flipper_length_mm,body_mass_g,sex
0,Adelie,Torgersen,39.1,18.7,181.0,3750.0,MALE
1,Adelie,Torgersen,39.5,17.4,186.0,3800.0,FEMALE
2,Adelie,Torgersen,40.3,18.0,195.0,3250.0,FEMALE
3,Adelie,Torgersen,NaN,NaN,NaN,NaN,NaN
4,Adelie,Torgersen,36.7,19.3,193.0,3450.0,FEMALE

In [5]:
print(dataset)

    species     island  culmen_length_mm  culmen_depth_mm  flipper_length_mm  \
0    Adelie  Torgersen              39.1             18.7              181.0
1    Adelie  Torgersen              39.5             17.4              186.0
2    Adelie  Torgersen              40.3             18.0              195.0
3    Adelie  Torgersen               NaN              NaN                NaN
4    Adelie  Torgersen              36.7             19.3              193.0
..      ...        ...               ...              ...                ...
339  Gentoo     Biscoe               NaN              NaN                NaN
340  Gentoo     Biscoe              46.8             14.3              215.0
341  Gentoo     Biscoe              50.4             15.7              222.0
342  Gentoo     Biscoe              45.2             14.8              212.0
343  Gentoo     Biscoe              49.9             16.1              213.0

     body_mass_g     sex
0         3750.0    MALE
1         3800.0  FEMALE
2         3250.0  FEMALE
3            NaN     NaN
4         3450.0  FEMALE
..           ...     ...
339          NaN     NaN
340       4850.0  FEMALE
341       5750.0    MALE
342       5200.0  FEMALE
343       5400.0    MALE

[344 rows x 7 columns]

In [9]:
print(dataset.isnull().sum())

species               0
island                0
culmen_length_mm      2
culmen_depth_mm       2
flipper_length_mm     2
body_mass_g           2
sex                  10
dtype: int64

In [10]:
dataset=dataset.dropna()
dataset.head()

,species,island,culmen_length_mm,culmen_depth_mm,flipper_length_mm,body_mass_g,sex
0,Adelie,Torgersen,39.1,18.7,181.0,3750.0,MALE
1,Adelie,Torgersen,39.5,17.4,186.0,3800.0,FEMALE
2,Adelie,Torgersen,40.3,18.0,195.0,3250.0,FEMALE
4,Adelie,Torgersen,36.7,19.3,193.0,3450.0,FEMALE
5,Adelie,Torgersen,39.3,20.6,190.0,3650.0,MALE

In [11]:
print(dataset)

    species     island  culmen_length_mm  culmen_depth_mm  flipper_length_mm  \
0    Adelie  Torgersen              39.1             18.7              181.0
1    Adelie  Torgersen              39.5             17.4              186.0
2    Adelie  Torgersen              40.3             18.0              195.0
4    Adelie  Torgersen              36.7             19.3              193.0
5    Adelie  Torgersen              39.3             20.6              190.0
..      ...        ...               ...              ...                ...
338  Gentoo     Biscoe              47.2             13.7              214.0
340  Gentoo     Biscoe              46.8             14.3              215.0
341  Gentoo     Biscoe              50.4             15.7              222.0
342  Gentoo     Biscoe              45.2             14.8              212.0
343  Gentoo     Biscoe              49.9             16.1              213.0

     body_mass_g     sex
0         3750.0    MALE
1         3800.0  FEMALE
2         3250.0  FEMALE
4         3450.0  FEMALE
5         3650.0    MALE
..           ...     ...
338       4925.0  FEMALE
340       4850.0  FEMALE
341       5750.0    MALE
342       5200.0  FEMALE
343       5400.0    MALE

[334 rows x 7 columns]

In [ ]:
# dataset=pd.read_csv(r'/content/drive/My Drive/ailab/penguins_size.csv')
# dataset=dataset.fillna(99)
#print(dataset)

In [ ]:
dataset['culmen_length_mm'].fillna(dataset['culmen_length_mm'].mean(), inplace=True)

In [12]:
dataset.dtypes

species               object
island                object
culmen_length_mm     float64
culmen_depth_mm      float64
flipper_length_mm    float64
body_mass_g          float64
sex                   object
dtype: object

In [13]:
dataset=pd.read_csv(r'/content/drive/My Drive/ailab/penguins_size.csv')
# dataset=dataset.fillna(99)
print(dataset)

    species     island  culmen_length_mm  culmen_depth_mm  flipper_length_mm  \
0    Adelie  Torgersen              39.1             18.7              181.0
1    Adelie  Torgersen              39.5             17.4              186.0
2    Adelie  Torgersen              40.3             18.0              195.0
3    Adelie  Torgersen               NaN              NaN                NaN
4    Adelie  Torgersen              36.7             19.3              193.0
..      ...        ...               ...              ...                ...
339  Gentoo     Biscoe               NaN              NaN                NaN
340  Gentoo     Biscoe              46.8             14.3              215.0
341  Gentoo     Biscoe              50.4             15.7              222.0
342  Gentoo     Biscoe              45.2             14.8              212.0
343  Gentoo     Biscoe              49.9             16.1              213.0

     body_mass_g     sex
0         3750.0    MALE
1         3800.0  FEMALE
2         3250.0  FEMALE
3            NaN     NaN
4         3450.0  FEMALE
..           ...     ...
339          NaN     NaN
340       4850.0  FEMALE
341       5750.0    MALE
342       5200.0  FEMALE
343       5400.0    MALE

[344 rows x 7 columns]

In [15]:
dataset.head()

,species,island,culmen_length_mm,culmen_depth_mm,flipper_length_mm,body_mass_g,sex
0,Adelie,Torgersen,39.10000,18.7,181.0,3750.0,MALE
1,Adelie,Torgersen,39.50000,17.4,186.0,3800.0,FEMALE
2,Adelie,Torgersen,40.30000,18.0,195.0,3250.0,FEMALE
3,Adelie,Torgersen,43.92193,NaN,NaN,NaN,NaN
4,Adelie,Torgersen,36.70000,19.3,193.0,3450.0,FEMALE

In [16]:
dataset['culmen_length_mm'].fillna(dataset['culmen_length_mm'].mean(), inplace=True)
dataset['culmen_depth_mm'].fillna(dataset['culmen_depth_mm'].mean(), inplace=True)
dataset['flipper_length_mm'].fillna(dataset['flipper_length_mm'].mean(), inplace=True)
dataset['body_mass_g'].fillna(dataset['body_mass_g'].mean(), inplace=True)

dataset['sex'].fillna(dataset['sex'].value_counts().index[0],inplace=True)
dataset.reset_index()
dataset.head()

,species,island,culmen_length_mm,culmen_depth_mm,flipper_length_mm,body_mass_g,sex
0,Adelie,Torgersen,39.10000,18.70000,181.0,3750.0,MALE
1,Adelie,Torgersen,39.50000,17.40000,186.0,3800.0,FEMALE
2,Adelie,Torgersen,40.30000,18.00000,195.0,3250.0,FEMALE
3,Adelie,Torgersen,43.92193,17.15117,NaN,NaN,NaN
4,Adelie,Torgersen,36.70000,19.30000,193.0,3450.0,FEMALE

In [17]:
dataset.dtypes

species               object
island                object
culmen_length_mm     float64
culmen_depth_mm      float64
flipper_length_mm    float64
body_mass_g          float64
sex                   object
dtype: object

In [18]:
dataset["species"]=dataset["species"].astype('category')
dataset["island"]=dataset["island"].astype('category')
dataset["sex"]=dataset["sex"].astype('category')

dataset.dtypes

species              category
island               category
culmen_length_mm      float64
culmen_depth_mm       float64
flipper_length_mm     float64
body_mass_g           float64
sex                  category
dtype: object

In [ ]:
#drop the columns of float64 datatype
#print df.headb

In [ ]:
from pandas.core.arrays import categorical
#label encoding for categrial data
categorical_data["species_cat"]=categorical_data["species"].cat.codes

In [ ]:
#one hot encoding

In [ ]:
#count encoding
#converts each categorical value into frequency